'use client'
import './globals.css'
import { Inter } from 'next/font/google'

import { Provider } from 'react-redux'
import store from './store'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })


const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <header className='container mx-auto text-center py-10 space-x-12'>
            <Link className='text-xl font-bold hover:opacity-50' href='/'>Homepage</Link>
            <Link className='text-xl font-bold hover:opacity-50' href='/users'>Users</Link>
            <Link className='text-xl font-bold hover:opacity-50' href='/sign'>Create User</Link>
        </header>
        <Provider store={store}>
          {children}
        </Provider>
      </body>
    </html>
  )
}
